site_name: Alan Liang
site_url: https://alanliangdev.github.io/
site_author: Alan Liang
site_description: Staff Platform Engineer specializing in AWS, DevOps, and Kubernetes solutions
copyright: "&copy; 2025 Alan Liang"

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Light mode  
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - blog:
      blog_dir: blog
      post_date_format: long
      post_url_format: "{date}/{slug}"
      post_readtime: true
      post_readtime_words_per_minute: 265
      categories_allowed:
        - AWS
        - Kubernetes
        - DevOps
        - Cloud
        - Platform Engineering
        - Cost Optimization
        - GitOps
        - CI/CD
        - ArgoCD
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/alanliangdev
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/alanliangdev/
  
extra_css:
  - stylesheets/custom.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css

nav:
  - Home: index.md
  - About: about.md
  - Blog: blog/index.md