site_name: Alan Liang
site_url: https://qoehliang.github.io/
site_author: Alan Liang
site_description: Staff Platform Engineer specializing in AWS, DevOps, and Kubernetes solutions

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.svg
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

plugins:
  - blog:
      blog_dir: blog
      post_date_format: long
      post_url_format: "{date}/{slug}"
      post_readtime: true
      post_readtime_words_per_minute: 265
      categories_allowed:
        - AWS
        - Kubernetes
        - DevOps
        - Cloud
        - Platform Engineering
        - Cost Optimization
        - GitOps
        - CI/CD
      categories_toc: true
      archive_toc: true
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/alan-liang
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/alan-liang
  
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - assets/js/theme-toggle.js

nav:
  - Home: index.md
  - Blog: 
      - blog/index.md