site_name: Alan Liang
site_url: https://alanliangdev.github.io/
site_author: Alan Liang
site_description: Staff Platform Engineer specializing in AWS, DevOps, and Kubernetes solutions
copyright: "&copy; 2025 Alan Liang"
repo_url: https://github.com/alanliangdev/alanliangdev.github.io
repo_name: alanliangdev/alanliangdev.github.io
edit_uri: ""

# 404 page
use_directory_urls: true

theme:
  name: material
  favicon: assets/favicon.svg
  icon:
    logo: material/cloud
  palette:
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Light mode  
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.code.copy
    - header.autohide
    - navigation.instant
    - navigation.footer

plugins:
  - blog:
      blog_dir: blog
      post_date_format: long
      post_url_format: "{date}/{slug}"
      post_readtime: true
      post_readtime_words_per_minute: 265
      categories_allowed:
        - AWS
        - Kubernetes
        - DevOps
        - Cloud
        - Platform Engineering
        - Cost Optimization
        - GitOps
        - CI/CD
        - ArgoCD
        - Security
        - Automation
        - Infrastructure
        - Monitoring
        - Observability
      authors_file: "{blog}/authors.yml"
      categories_name: Categories
      categories_url_format: "category/{slug}"
      categories_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      archive: true
      archive_name: Archive
      archive_date_format: "%Y"
      archive_url_format: "archive/{date}"
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
      lang: en
      indexing: 'full'

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/alanliangdev
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/alanliangdev/
  
extra_css:
  - stylesheets/custom.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css

extra_javascript:
  - assets/js/theme-toggle.js
  - assets/js/portfolio-filter.js
  - assets/js/blog-filter.js
  - assets/js/blog-search.js

nav:
  - Home: index.md
  - About: about.md
  - Resume: resume.md
  - Portfolio: 
    - Overview: portfolio.md
    - Projects:
      - Enterprise Kubernetes Platform: portfolio/kubernetes-platform.md
      - Cloud Migration & Cost Optimization: portfolio/aws-migration.md
      - GitOps CI/CD Pipeline: portfolio/gitops-pipeline.md
      - Observability Platform: portfolio/observability-platform.md
      - Infrastructure as Code Framework: portfolio/iac-framework.md
      - Security & Compliance Automation: portfolio/security-automation.md
  - Blog: blog/index.md