authors:
  alan:
    name: Alan Liang
    description: Staff Platform Engineer at Commonwealth Bank of Australia
    avatar: https://www.gravatar.com/avatar/00000000000000000000000000000000?d=mp
    url: https://github.com/alan-liang